version: '3'
services:
  #MySQL Service
  saintseiyadb:
    image: mysql:8.0
    container_name: saint-seiya-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: saintseiya
      MYSQL_ROOT_PASSWORD: saintseiyapass
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/my.cnf
    networks:
      - network-saint-seiya

  #PHP Service
  saga:
    build:
      context: ../saga/
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: saga-api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ../saga/:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - network-saint-seiya

  #Nginx Service
  doko:
    image: nginx:alpine
    container_name: doko-php-ngnix
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../saga/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - network-saint-seiya

#Docker Networks
networks:
  network-saint-seiya:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
